language: rust

#sudo: false
#
#addons:
#  apt:
#    packages:
#      # rsmpi dependencies
#      - mpich2
#      - libclang-3.4-dev
#      # travis-cargo dependencies
#      - libcurl4-openssl-dev
#      - libelf-dev
#      - libdw-dev

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y mpich2 libclang-3.4-dev libcurl4-openssl-dev libelf-dev libdw-dev

rust:
  - beta
  - stable

env:
  global:
    - LIBCLANG_PATH=/usr/lib/llvm-3.4/lib

before_script:
  - |
      pip install 'travis-cargo<0.2' --user &&
      export "PATH=$HOME/.local/bin:$PATH"

script:
  - |
      travis-cargo build &&
      travis-cargo test &&
      travis-cargo --only stable doc
