language: rust

sudo: false

addons:
  apt:
    packages:
      # for building MPI libraries
      - build-essential
      - gfortran
      # bindgen dependency
      - libclang-3.4-dev

rust:
  - stable
  #- beta

env:
  matrix:
    - MPI_LIBRARY=mpich MPI_LIBRARY_VERSION=3.1.4
    #- MPI_LIBRARY=mpich MPI_LIBRARY_VERSION=3.0.4
    #- MPI_LIBRARY=openmpi MPI_LIBRARY_VERSION=1.8.7
  global:
    - DOC_LIBRARY=mpich
    - DOC_LIBRARY_VERSION=3.1.4
    - LIBCLANG_PATH=/usr/lib/llvm-3.4/lib
    - secure: "hbB6EhELjgI79FKuov4M11ZWiIIZLyOikV+gcE9KpoedLgHbnhSgpbSBlMZ6QFbsXKNAFX7uHlnNkweqJB+pMHYCL8qL9Vxu4vFd1YRyexJSRo7Ly9T7U0aFYR7XCIboCwu26BKqWRPioWL/3W+e0dFctPDZ9Fp1dlFOGZKW1aAMC15r0ekFY0z7lvY4ph2eA45EygKyYnM3t1VAEzk+vq1cRqOL8zRpkB0ydeLkgW0JUWzM+tLdZCou7bsoqwPGEQgx+rUpBSpDEuB5FW0Bbbyhwhc5B1NKVLSTXpwKYY5sVG2YnC4B/hatagLUUpvXb0ncxzFah5rFL/qNZMiP2MB3G6Xn7SBZhapbnYClc7nsBsk8SQlSCKTnq6ypU1/0ZhR/UKhfZK4Yb5+k1TdQ4MeQUj+6elJOKmnIcrUQxGqVxFjuY5WarARjgyDoeG50iXqmVtC0jDdqpHEahIEzCHj79/KIiARsHss3Hm+eblRaWEQZzUzCSFQhoIUH1rzdSJ2twQyEpGpVVTttQjIGVRdhtute98NyvPz6Mk0hE9HO2m/RnYKieI3NG0TUzDkLANFYic/L8YxSek5uoJaZ3MNfEKELYxvZE7rtKm1TyDpwyJEDO7Sx2jSNX7ahqTX+e6a0so93vE+Wt5BlR9R6oVj7v9H9HfsGeTKpiis1Ol8="

install:
  - sh ci/install-mpi.sh
  - pip install 'ghp-import' --user
  - export MPI_PREFIX="${HOME}/opt/${MPI_LIBRARY}-${MPI_LIBRARY_VERSION}"
  - export PATH="${HOME}/.local/bin:${MPI_PREFIX}/bin${PATH:+":${PATH}"}"
  - export LD_LIBRARY_PATH="${MPI_PREFIX}/lib${LD_LIBRARY_PATH:+":${LD_LIBRARY_PATH}"}"

script:
  - cargo -v build && cargo -v test

before_deploy:
  - touch ci/deploy_key && chmod 0600 ci/deploy_key
  - openssl aes-256-cbc -K $encrypted_bf29288dac26_key -iv $encrypted_bf29288dac26_iv -in ci/deploy_key.enc -out ci/deploy_key -d
  - echo -e "Host github.com\n  IdentityFile $(pwd)/ci/deploy_key" >> ${HOME}/.ssh/config
  - git remote set-url origin git@github.com:bsteinb/rsmpi.git

deploy:
  provider: script
  script: ci/deploy-docs.sh
  skip_cleanup: true
  on:
    branch: master
    condition: "${MPI_LIBRARY} = ${DOC_LIBRARY} && ${MPI_LIBRARY_VERSION} = ${DOC_LIBRARY_VERSION} && ${TRAVIS_RUST_VERSION} = stable"

cache:
  directories:
    - $HOME/opt
