language: rust

sudo: false

addons:
  apt:
    packages:
      # rsmpi dependencies
      - openmpi
      - libclang-3.4-dev
      # travis-cargo dependencies
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev


rust:
  - beta
  - stable

env:
  global:
    - LIBCLANG_PATH=/usr/lib/x86_64-linux-gnu

before_script:
  - |
      pip install 'travis-cargo<0.2' --user &&
      export "PATH=$HOME/.local/bin:$PATH"

script:
  - |
      travis-cargo build &&
      travis-cargo test &&
      travis-cargo --only stable doc
