[package]
name = "mpi"
version = "0.1.5"
authors = ["Benedikt Steinbusch <benedikt.steinbusch@googlemail.com>"]
description = "Message Passing Interface bindings for Rust"

homepage = "https://github.com/bsteinb/rsmpi"
repository = "https://github.com/bsteinb/rsmpi"
documentation = "http://bsteinb.github.io/rsmpi/"

readme = "README.md"

keywords = [ "message-passing", "distributed memory", "parallel" ]

license = "MIT"

build = "build.rs"

[dependencies]
libc = "0.1.10"

[build-dependencies]
gcc = "0.3.13"
bindgen = "0.15.0"

#[dependencies.c_import]
#git = "https://github.com/vojtechkral/rust-c-import.git"
