[package]
name = "mpi"
version = "0.4.0"
authors = ["Benedikt Steinbusch <ben@rockshrub.de>"]
description = "Message Passing Interface bindings for Rust"
homepage = "https://github.com/bsteinb/rsmpi"
repository = "https://github.com/bsteinb/rsmpi"
documentation = "http://bsteinb.github.io/rsmpi/"
readme = "README.md"
keywords = [ "message-passing", "parallel" ]
license = "MIT OR Apache-2.0"
build = "build.rs"

[dependencies]
conv = "0.3"
clippy = { version = "0.0.43", optional = true }

[build-dependencies]
gcc = "0.3"
bindgen = { git = "https://github.com/japaric/rust-bindgen.git", rev = "19043ea5d8a525b6b8de211ff63f4b6a406fcb49" }
build-probe-mpi = { path = "./build-probe-mpi" }

#[dependencies.c_import]
#git = "https://github.com/vojtechkral/rust-c-import.git"

[features]
default=[]
