[package]
name = "mpi"
version = "0.6.0"
authors = [
    "Benedikt Steinbusch <ben@rockshrub.de>",
    "Andrew Gaspar <andrew.gaspar@outlook.com>"
]
description = "Message Passing Interface bindings for Rust"
homepage = "https://github.com/bsteinb/rsmpi"
repository = "https://github.com/bsteinb/rsmpi"
documentation = "http://bsteinb.github.io/rsmpi/"
readme = "README.md"
keywords = [ "message-passing", "parallel" ]
categories = [ "concurrency" ]
license = "MIT/Apache-2.0"
edition = "2018"

[workspace]
members = ["mpi-derive"]

[features]
default = []

user-operations = ["libffi"]
derive = ["mpi-derive"]

[[example]]
name = "struct"
required-features = ["derive"]

[dependencies]
conv = "0.3"
libffi = { version = "0.8.0", optional = true }
mpi-derive = { path = "mpi-derive", optional = true }
mpi-sys = { path = "mpi-sys", version = "0.2" }
smallvec = "1.0.0"
# TODO: This needs to be a real version before this is merged
memoffset = { git = "https://github.com/AndrewGaspar/memoffset.git", branch = "tuple-offset" }

[build-dependencies]
rustc_version = "0.2"
