[package]
name = "mpi-derive"
version = "0.1.0"
authors = ["Andrew Gaspar <andrew.gaspar@outlook.com>"]

[lib]
proc-macro = true

[dependencies]
syn = "0.15.9"
quote = "0.6.8"
proc-macro2 = "0.4.19"

[dependencies.mpi]
path = ".."
version = "0.5"
default-features = false